name: Build Flutter APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./nexqa_flutter_factory_auth/nexqa_flutter
        run: flutter pub get

      - name: Build APK
        working-directory: ./nexqa_flutter_factory_auth/nexqa_flutter
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./nexqa_flutter_factory_auth/nexqa_flutter/build/app/outputs/flutter-apk/app-release.apk
